#!/usr/bin/env bash

PS3='Please enter your choice: '
options=("Django NuxtJS Docusaurus" "Django" "PostgreSQL" "NuxtJS" "Quit")
command="cookiecutter gh:IgnisDa/project-cookiecutter --directory"
select opt in "${options[@]}"; do
    case $opt in
        "Django NuxtJS Docusaurus")
	    command="$command django-nuxt-docusaurus"
            eval $command
	    break
            ;;
        "Django")
	    command="$command django"
            eval $command
	    break
            ;;
        "PostgreSQL")
	    command="$command postgres"
            eval $command
	    break
            ;;
        "NuxtJS")
	    command="$command nuxt"
            eval $command
	    break
            ;;
	"Quit")
	    echo "User requested exit"
	    exit
	    ;;
        *) echo "invalid option $REPLY";;
    esac
done
